language: ruby
rvm:
- 2.3.0
script:
- gem install simplecov
- gem install coveralls
- gem install fivemat
- rake test
deploy:
  provider: rubygems
  api_key:
    secure: gtbnJJ6MgaVI/6RoKCioJXeGzrCQ3/cTYVNUTRXDa476BgpsYmIbAtA5zGbYoTsjw5BMEs89M8zLjbdFY9VdZUAw9SlnrLZLEuLQa3PukR5A6SxI2Cu6dGZpLt4kr7xZK5YLyN4dqcQPtwJb5FbN4v2X5hcwWDF8NrpcCXp55kt+tGxUUHExskW9sBtFguBjH58XKKxuykO4wvDj+u7IG8gl/3Aep0zPGNB1Iy51doEe+5EmWYTLJKELfXFfdJsrGM/eNs1hboWQ+kPPVjVJ2Yen8Z74zLe+pMz2L1bXo8kCU/IZyC1BrxHH62OFPb8k0SoV+iEVk070XEVp70p5nMYmitOzXp2riIi/0sq9CUaqGsrzLKDZ+Fbgug59b/jRBJSPmeh/rmo5OJ7dUmarZtxriBaryYOuOQzQRouLKwEdYA05U7HI3q9CNRWnf0Gho5seWJ9ahiIhnE2A214Ys1UdHScJsqyGO89lEjIT9mV0To+7CbVz5OY2rAVDYiVu2DIgRG0BLXP5yg41AbXOk83n1b4BXjEIApiGtJjWfupJLVOpldHK4/AwfMupchBdH1EsLuT9JfBM5tbQeJ3uvshT7Wl9gZ1/UtCJA5qsW9FxrRunsGCNpM1oImFFk+VlFbg518A/h7LiS8HX2hiU/aMdamEJiYl4EMshcaQaw+I=
  gem: open_string
  on:
    tags: true
    repo: jrconner384/open_string
